import { UserProvider } from "@/lib/context/user-context";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <NuqsAdapter>{children}</NuqsAdapter>
        </UserProvider>
      </body>
    </html>
  );
}
